routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;

use App\Http\livewire\RolController;
use App\Http\livewire\ServicioController;
use App\Http\livewire\TipoPacienteController;
use App\Http\livewire\EspecialidadController;
use App\Http\Livewire\MedicamentoController;
use App\Http\Livewire\RecetaMedicaController;
use App\Http\Livewire\MedicoController;
use App\Http\Livewire\PacienteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/admin', function () {
    return view('admin.dashboard');
});*/



Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});


Route::get('/login', [App\Http\Controllers\LoginController::class, 'show'])->name('login');
Route::post('/login', [App\Http\Controllers\LoginController::class, 'login'])->name('login.perform');

Route::middleware(['middleware' => 'auth'])->group(function() {
    //convocatoria
    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'admin'],
        function () {

            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            //Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.rol');
            Route::resource('/roles', RolController::class);
            Route::resource('/servicios', ServicioController::class);
            Route::resource('/tipo-paciente', TipoPacienteController::class);
            Route::resource('/especialidad', EspecialidadController::class);
            Route::resource('/medicamento', MedicamentoController::class);
            Route::resource('/receta-medica', RecetaMedicaController::class);
            Route::resource('/medicos', MedicoController::class);
            Route::resource('/pacientes', PacienteController::class);
        });

    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'empleado'],
        function () {

            //Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            //Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index1'])->name('home1');

        });
    });

//Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    /*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');*/
//});

app/Models/TipoPaciente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TipoPaciente extends Model
{
    use HasFactory;
    protected $fillable = ['id', 'tipo_paciente', 'descripcion', 'estado', 'created_at', 'updated_at'];

    public function pacientes(){
        return $this->hasMany('App\Models\Paciente');
    }
}

app/Http/Livewire/PacienteController.php
<?php

namespace App\Http\Livewire;

use App\Models\Especialidad;
use App\Models\Medico;
use App\Models\Paciente;
use App\Models\Persona;
use App\Models\TipoPaciente;
use Livewire\Component;
use Livewire\WithPagination;

class PacienteController extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $listeners = ['render', 'destroy'];

    public $selected_id;
    public $accion;
    public $dni, $nombres, $apellido_materno, $apellido_paterno, $fecha_nacimiento, $celular, $correo, $genero,
        $ocupacion, $tipo_paciente_id, $persona_id, $created_at, $updated_at;
    public $search;
    public $cantidad = 10;
    public $sort = 'id';
    public $order = 'desc';


    protected $rules = [
        'dni'               => 'required',
        'nombres'           => 'required',
        'apellido_materno'  => 'required',
        'apellido_paterno'  => 'required',
        'fecha_nacimiento'  => 'required',
        'correo'  => 'required',
        'genero'  => 'required',
        'ocupacion'  => 'required',
        'tipo_paciente_id'  => 'required',
        'celular' => 'required'
    ];

    protected $msjError=[
        'dni.required' => 'El campo DNI es obligatorio.',
        'nombres.required' => 'El campo nombres es obligatorio.',
        'apellido_materno.required' => 'El campo apellido materno es obligatorio.',
        'apellido_paterno.required' => 'El campo apellido paterno es obligatorio.',
        //'celular.required' => 'El campo especialidad es obligatorio.',
        //'codigo_medicos.required' => 'El campo código de medico es obligatorio.'
    ];

    public function render()
    {
        $cbo_tipo_paciente = TipoPaciente::where('estado', 1)->get();

        $pacientes = Paciente::select('pacientes.id', 'pacientes.persona_id', 'pacientes.tipo_paciente_id', 'pacientes.ocupacion', 'pacientes.fecha_registro', 'pacientes.estado',
        'persona.dni','persona.nombres','persona.apellido_paterno','persona.apellido_materno','persona.fecha_nacimiento', 'persona.celular', 'persona.correo', 'persona.genero',
        'tipo_pacientes.tipo_paciente')
            ->join('persona', 'pacientes.persona_id', '=', 'persona.id')
            ->join('tipo_pacientes', 'pacientes.tipo_paciente_id', '=', 'tipo_pacientes.id')
            ->where('persona.nombres', 'like', '%' . $this->search . '%')
            ->orderBy($this->sort, $this->order)
            ->paginate($this->cantidad);
        //dd($data);
        return view('admin.pacientes.view', compact('pacientes', 'cbo_tipo_paciente'));
    }

    public function index()
    {
        return view('admin.pacientes.index');
    }

    public function create(){
        $this->resetUI();
        $this->emit('show-modal-paciente', 'mostrar modal');
    }

    public function store(){
        $this->validate($this->rules, $this->msjError);
        $persona_insertado = Persona::create([
            'dni' => $this->dni,
            'nombres' => $this->nombres,
            'apellido_paterno' => $this->apellido_paterno,
            'apellido_materno' => $this->apellido_materno,
            'fecha_nacimiento' => $this->fecha_nacimiento,
            'celular' => $this->celular,
            'correo' => $this->correo,
            'genero' => $this->genero,
            'estado' => 1,
            'created_at'=>now(),
            'updated_at'=>null
        ]);

        $this->persona_id = $persona_insertado->id;

        $persona_insertado = Paciente::create([
            'persona_id' => $this->persona_id,
            'tipo_paciente_id' => $this->tipo_paciente_id,
            'ocupacion' => $this->ocupacion,
            'fecha_registro' => now(),
            'estado' => 1,
            'created_at'=>now(),
            'updated_at'=>null
        ]);



        $this->resetUI();
        $this->emit('paciente-add-close', 'Servicio Registrado');
        $this->dispatchBrowserEvent('alert',
            ['type' => 'success',  'message' => 'Registro exitoso!']);

    }

    public function edit($id){
        $this->selected_id = $id;
        $paciente = Paciente::find($id);
        $this->persona_id = $paciente->persona_id;
        $this->tipo_paciente_id = $paciente->tipo_paciente_id;
        $this->ocupacion = $paciente->ocupacion;

        $persona = Persona::find($this->persona_id);
        $this->dni = $persona->dni;
        $this->nombres = $persona->nombres;
        $this->apellido_paterno = $persona->apellido_paterno;
        $this->apellido_materno = $persona->apellido_materno;
        $this->fecha_nacimiento = $persona->fecha_nacimiento;
        $this->celular =$persona->celular;
        $this->correo =$persona->correo;
        $this->genero =$persona->genero;
        $this->emit('show-modal-paciente', 'mostrar modal');
    }

    public function update()
    {
        $this->validate($this->rules, $this->msjError);

        if ($this->selected_id) {
            $record = Paciente::find($this->selected_id);
            $record->update([
                'persona_id' => $this->persona_id,
                'tipo_paciente_id' => $this->tipo_paciente_id,
                'ocupacion' => $this->ocupacion,
                'updated_at'=>now()
            ]);

            $record = Persona::find($this->persona_id);
            $record->update([
                'dni' => $this->dni,
                'nombres' => $this->nombres,
                'apellido_paterno' => $this->apellido_paterno,
                'apellido_materno' => $this->apellido_materno,
                'fecha_nacimiento' => $this->fecha_nacimiento,
                'celular' => $this->celular,
                'correo' => $this->correo,
                'genero' => $this->genero,
                'updated_at'=>now()
            ]);

            $this->resetUI();
            $this->emit('paciente-add-close', 'Rol Actualizado');
            $this->dispatchBrowserEvent('alert',
                ['type' => 'success',  'message' => 'Actualización exitoso!']);
        }
    }

    public function deleteForm($id, $accion){
        $this->selected_id = $id;
        $this->accion = $accion;
        $this->emit('info-alert-modal', 'mostrar modal');
    }

    public function cancelarEliminado(){
        $this->selected_id = null;
        $this->emit('info-alert-modal-close', 'mostrar modal');
    }

    public function closeModal(){
        $this->resetUI();
        $this->emit('paciente-add-close', 'Rol Actualizado');
    }

    public function eliminar()
    {
        if ($this->selected_id) {
            if ($this->accion=='desactivar'){
                $record = Paciente::find($this->selected_id);
                $record->update([
                    'estado' => 0
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Eliminado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Eliminado!']);
            } else{
                $record = Paciente::find($this->selected_id);
                $record->update([
                    'estado' => 1
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Activado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Activado!']);
            }

        }
    }

    public function closeModalShow(){
        $this->resetUI();
        $this->emit('pacienteshow-add-close', 'Rol Actualizado');
    }


    public function show($id){
        $this->selected_id = $id;
        $paciente = Paciente::find($id);
        $this->persona_id = $paciente->persona_id;
        $this->tipo_paciente_id = $paciente->tipo_paciente_id;
        $this->ocupacion = $paciente->ocupacion;

        $persona = Persona::find($this->persona_id);
        $this->dni = $persona->dni;
        $this->nombres = $persona->nombres;
        $this->apellido_paterno = $persona->apellido_paterno;
        $this->apellido_materno = $persona->apellido_materno;
        $this->fecha_nacimiento = $persona->fecha_nacimiento;
        $this->celular =$persona->celular;
        $this->correo =$persona->correo;
        $this->genero =$persona->genero;
        $this->emit('show-modal-pacienteshow', 'mostrar modal');
    }

    public function resetUI(){
        $this->dni=null;
        $this->nombres=null;
        $this->apellido_materno=null;
        $this->apellido_paterno=null;
        $this->fecha_nacimiento=null;
        $this->celular=null;
        $this->correo=null;
        $this->genero=null;
        $this->persona_id=null;
        $this->tipo_paciente_id=null;
        $this->ocupacion = null;
        $this->selected_id=null;
        $this->accion=null;
        $this->resetValidation();
    }
}

app/Http/Livewire/TipoPacienteController.php
<?php

namespace App\Http\Livewire;

use App\Models\TipoPaciente;
use Livewire\Component;
use Livewire\WithPagination;

class TipoPacienteController extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $listeners = ['render', 'destroy'];

    public $selected_id;
    public $accion;
    public $tipo_paciente, $descripcion, $precio, $estado, $created_at, $updated_at;
    public $search;
    public $cantidad = 10;
    public $sort = 'id';
    public $order = 'desc';


    protected $rules = [
        'tipo_paciente' => 'required',
        'tipo_paciente' => 'required|alpha',
        'descripcion'   => 'required',
    ];

    protected $msjError=[
        'tipo_paciente.required' => 'El campo tipo paciente es obligatorio.',
        'tipo_paciente.alpha' => 'El tipo paciente solo debe contener letras.',
        'descripcion.required' => 'El campo descripción es obligatorio.'
    ];

    public function render()
    {
        $tipo_pacientes = TipoPaciente::where('tipo_paciente', 'like', '%' . $this->search . '%')
            ->orderBy($this->sort, $this->order)
            ->paginate($this->cantidad);
        return view('admin.tipo-paciente.view', compact('tipo_pacientes'));
    }

    public function index()
    {
        return view('admin.tipo-paciente.index');
    }

    public function create(){
        $this->resetUI();
        $this->emit('show-modal-tpaciente', 'mostrar modal');
    }

    public function store(){

        $this->validate($this->rules, $this->msjError);
        TipoPaciente::create([
            'tipo_paciente' => $this->tipo_paciente,
            'descripcion' => $this->descripcion,
            'estado' => 1,
            'created_at'=>now(),
            'updated_at'=>null
        ]);

        $this->resetUI();
        $this->emit('tpaciente-add-close', 'Servicio Registrado');
        $this->dispatchBrowserEvent('alert',
            ['type' => 'success',  'message' => 'Registro exitoso!']);

    }

    public function edit($id){
        $this->selected_id = $id;
        $rol = TipoPaciente::find($id);
        $this->tipo_paciente = $rol->tipo_paciente;
        $this->descripcion =$rol->descripcion;
        $this->emit('show-modal-tpaciente', 'mostrar modal');
    }

    public function update()
    {
        $this->validate($this->rules, $this->msjError);

        if ($this->selected_id) {
            $record = TipoPaciente::find($this->selected_id);
            $record->update([
                'tipo_paciente' => $this->tipo_paciente,
                'descripcion' => $this->descripcion,
                'created_at'=>null,
                'updated_at'=>now()
            ]);

            $this->resetUI();
            $this->emit('tpaciente-add-close', 'Rol Actualizado');
            $this->dispatchBrowserEvent('alert',
                ['type' => 'success',  'message' => 'Actualización exitoso!']);
        }
    }

    public function deleteForm($id, $accion){
        $this->selected_id = $id;
        $this->accion = $accion;
        $this->emit('info-alert-modal', 'mostrar modal');
    }

    public function cancelarEliminado(){
        $this->selected_id = null;
        $this->emit('info-alert-modal-close', 'mostrar modal');
    }

    public function closeModal(){
        $this->resetUI();
        $this->emit('tpaciente-add-close', 'Rol Actualizado');
    }

    public function resetUI(){
        $this->tipo_paciente=null;
        $this->precio=null;
        $this->descripcion=null;
        $this->selected_id=null;
        $this->accion=null;
        $this->resetValidation();
    }

    public function eliminar()
    {
        //dd($this->accion);
        if ($this->selected_id) {
            if ($this->accion=='desactivar'){
                $record = TipoPaciente::find($this->selected_id);
                $record->update([
                    'estado' => 0
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Eliminado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Eliminado!']);
            } else{
                $record = TipoPaciente::find($this->selected_id);
                $record->update([
                    'estado' => 1
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Activado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Activado!']);
            }

        }
    }
}

resources/views/admin/tipo-paciente/form.blade.php
<div wire:ignore.self id="con-close-modal-tpaciente" class="modal fade" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                @if(!$selected_id)
                    {{--<h4 class="modal-title">{{$title}}</h4>--}}
                    <h4 class="modal-title">TIPO PACIENTE | REGISTRAR</h4>
                @else
                    <h4 class="modal-title">TIPO PACIENTE | EDITAR</h4>
                @endif
                {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Tipo Paciente</label>
                            <input wire:model.lazy="tipo_paciente" type="text" class="form-control" id="field-3" placeholder="Tipo Paciente" maxlength="150" oninput="this.value = this.value.replace(/[^a-zA]/,'')">
                            @error('tipo_paciente')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <label for="field-7" class="control-label">Descripción</label>
                            <textarea wire:model.lazy="descripcion" class="form-control" id="field-7" placeholder="Descripción" maxlength="250"></textarea>
                            @error('descripcion')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button wire:click="closeModal()" type="button" class="btn btn-secondary waves-effect">CANCELAR</button>
                @if(!$selected_id)
                    <button wire:click.prevent="store()" type="button" class="btn btn-primary waves-effect waves-light">REGISTRAR</button>
                @else
                    <button wire:click.prevent="update()" type="button" class="btn btn-primary waves-effect waves-light">ACTUALIZAR</button>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/admin/tipo-paciente/index.blade.php
@extends('admin.layout.app_admin')
@section('content')
    @livewire('tipo-paciente-controller')
@endsection

resources/views/admin/tipo-paciente/view.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                        <li class="breadcrumb-item active">Starter</li>
                    </ol>
                </div>
                <h4 class="page-title">Tipo Paciente</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-6 col-md-8 col-lg-8">
                        <div class="form-group">
                            <label for="inputPassword2" class="sr-only">Search</label>
                            <input wire:model="search" type="search" class="form-control" id="inputPassword2" placeholder="Search...">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="text-lg-right mt-3 mt-lg-0">
                            {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal">Info Alert</button>--}}
                            <button wire:click="create()" type="button" class="btn btn-success waves-effect waves-light mr-1" ><i class="mdi mdi-plus-circle mr-1"></i> AGREGAR</button>
                        </div>
                    </div><!-- end col-->
                </div>
                <div class="responsive-table-plugin">
                    {{--<div class="table-rep-plugin">--}}
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>N°</th>
                                <th>TIPO PACIENTE</th>
                                <th>DESCRIPCIÓN </th>
                                <th>FECHA CREACIÓN</th>
                                <th>ESTADO</th>
                                <th>OPCIONES</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($tipo_pacientes as $tipo_paciente)
                                <tr>
                                    <td>{{(($tipo_pacientes->currentpage()-1)*$cantidad) + $loop->iteration }}</td>
                                    <th class="text-uppercase"><span class="co-name">{{$tipo_paciente->tipo_paciente}}</span></th>
                                    <td>{{$tipo_paciente->descripcion}}</td>
                                    <td>{{$tipo_paciente->created_at}}</td>
                                    <td>
                                        @if($tipo_paciente->estado==1)
                                        <span class="badge bg-soft-success text-success">ACTIVADO</span>
                                        @else
                                            <span class="badge bg-soft-danger text-danger">DESACTIVADO</span>
                                        @endif
                                    </td>
                                    <td>
                                        {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal{{ $loop->iteration }}">Info Alert</button>--}}
                                        <button wire:click="edit({{$tipo_paciente->id}})" type="button" class="btn btn-blue btn-sm waves-effect waves-light"><i class="fas fa-pen"></i></button>
                                        @if($tipo_paciente->estado==1)
                                        <button wire:click="deleteForm({{$tipo_paciente->id}}, 'desactivar')" type="button" class="btn btn-danger btn-sm" ><i class="fas fa-trash-alt"></i></button>
                                        @else
                                            <button wire:click="deleteForm({{$tipo_paciente->id}}, 'activar')" type="button" class="btn btn-success btn-sm" ><i class="fas fa-check-circle"></i></button>
                                        @endif
                                    </td>
                                </tr>
                                @include('admin.common.delete-dialog')
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{--</div>--}}
                    <nav class="p-1">
                        <ul class="justify-content-start">
                            {{$tipo_pacientes->firstItem()}}
                            a {{$tipo_pacientes->lastItem()}} de {{$tipo_pacientes->total()}} entradas
                        </ul>
                        <ul class="pagination justify-content-end">

                            {{$tipo_pacientes->links()}}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    @include('admin.tipo-paciente.form')


</div>

<script>
    document.addEventListener('DOMContentLoaded', function (){
        window.livewire.on('tpaciente-add-close', msg=>{
            $('#con-close-modal-tpaciente').modal('hide')
        });

        window.livewire.on('show-modal-tpaciente', msg=>{
            $('#con-close-modal-tpaciente').modal('show')
        });

        window.livewire.on('info-alert-modal', msg=>{
            $('#info-alert-modal').modal('show')
        });

        window.livewire.on('info-alert-modal-close', msg=>{
            $('#info-alert-modal').modal('hide')
        });
    });
</script>