routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;

use App\Http\livewire\RolController;
use App\Http\livewire\ServicioController;
use App\Http\livewire\TipoPacienteController;
use App\Http\livewire\EspecialidadController;
use App\Http\Livewire\MedicamentoController;
use App\Http\Livewire\RecetaMedicaController;
use App\Http\Livewire\MedicoController;
use App\Http\Livewire\PacienteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/admin', function () {
    return view('admin.dashboard');
});*/



Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});


Route::get('/login', [App\Http\Controllers\LoginController::class, 'show'])->name('login');
Route::post('/login', [App\Http\Controllers\LoginController::class, 'login'])->name('login.perform');

Route::middleware(['middleware' => 'auth'])->group(function() {
    //convocatoria
    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'admin'],
        function () {

            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            //Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.rol');
            Route::resource('/roles', RolController::class);
            Route::resource('/servicios', ServicioController::class);
            Route::resource('/tipo-paciente', TipoPacienteController::class);
            Route::resource('/especialidad', EspecialidadController::class);
            Route::resource('/medicamento', MedicamentoController::class);
            Route::resource('/receta-medica', RecetaMedicaController::class);
            Route::resource('/medicos', MedicoController::class);
            Route::resource('/pacientes', PacienteController::class);
        });

    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'empleado'],
        function () {

            //Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            //Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index1'])->name('home1');

        });
    });

//Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    /*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');*/
//});

app/Http/Livewire/RolController.php
<?php

namespace App\Http\Livewire;

use App\Models\Rol;
use Livewire\Component;
use Livewire\WithPagination;

class RolController extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    public $title = "Xfiiiiiiiiiiiiin";
    public $accion;

    public $members = 'members';
    public $selected_id;
    public $nombreRol;
    public $descripcion;
    public $search;
    public $cantidad=5;
    public $sort='id';
    public $order='desc';

    protected $listeners = ['render', 'destroy'];
    protected $rules = [
        'nombreRol'       => 'required',
        'descripcion'   => 'required',
    ];

    protected $msjError=[
        'nombreRol.required' => 'El campo rol es obligatorio.',
        'descripcion.required' => 'El campo dwcripción es obligatorio.'
    ];

    public function render()
    {
        $roles = Rol::where('rol','like','%'.$this->search.'%')
        ->orderBy($this->sort,$this->order)
        ->paginate($this->cantidad);
        return view('admin.roles.listar', compact('roles'));
    }

    public function index()
    {
        return view('admin.roles.index');
    }

    public function store(){

        $this->validate($this->rules, $this->msjError);
        Rol::create([
            'rol' => $this->nombreRol,
            'descripcion' => $this->descripcion,
            'created_at'=>now(),
            'updated_at'=>null
        ]);

        $this->resetUI();
        $this->emit('rol-add', 'Rol Registrado');
        $this->dispatchBrowserEvent('alert',
            ['type' => 'success',  'message' => 'Registro exitoso!']);

    }

    public function resetUI(){
        $this->nombreRol='';
        $this->descripcion='';
        $this->selected_id=null;
        $this->resetValidation();
    }

    public function edit($id){
        $this->selected_id = $id;
        $rol = Rol::find($id);
        $this->nombreRol = $rol->rol;
        $this->descripcion =$rol->descripcion;
        $this->emit('show-modal', 'mostrar modal');
    }

    public function update()
    {
        $this->validate($this->rules, $this->msjError);

        if ($this->selected_id) {
            $record = Rol::find($this->selected_id);
            $record->update([
                'rol' => $this->nombreRol,
                'descripcion' => $this->descripcion,
                'created_at'=>null,
                'updated_at'=>now()
            ]);

            $this->resetUI();
            $this->emit('rol-add', 'Rol Actualizado');
            $this->dispatchBrowserEvent('alert',
                ['type' => 'success',  'message' => 'Registro exitoso!']);
        }
    }

    /*public function alertSuccess()
    {
        $this->dispatchBrowserEvent('alert',
            ['type' => 'success',  'message' => 'User Created Successfully!']);
    }

    public function alertError()
    {
        $this->dispatchBrowserEvent('alert',
            ['type' => 'error',  'message' => 'Something is Wrong!']);
    }

    public function alertInfo()
    {
        $this->dispatchBrowserEvent('alert',
            ['type' => 'info',  'message' => 'Going Well!']);
    }*/
}

resources/views/admin/roles/create.blade.php
<div wire:ignore.self id="con-close-modal" class="modal fade" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                @if(!$selected_id)
                {{--<h4 class="modal-title">{{$title}}</h4>--}}
                    <h4 class="modal-title">ROL | REGISTRAR</h4>
                @else
                <h4 class="modal-title">ROL | EDITAR</h4>
                @endif
                {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Nombre Rol</label>
                            <input wire:model.lazy="nombreRol" type="text" class="form-control" id="field-3" placeholder="Nombre Rol">
                            @error('nombreRol')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <label for="field-7" class="control-label">Descripción</label>
                            <textarea wire:model.lazy="descripcion" class="form-control" id="field-7" placeholder="Descripcion Rol"></textarea>
                            @error('descripcion')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button wire:click="resetUI()" type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">CANCELAR</button>
                @if(!$selected_id)
                    <button wire:click.prevent="store()" type="button" class="btn btn-primary waves-effect waves-light">REGISTRAR</button>
                @else
                    <button wire:click.prevent="update()" type="button" class="btn btn-primary waves-effect waves-light">ACTUALIZAR</button>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/admin/roles/index.blade.php
@extends('admin.layout.app_admin')
@section('content')

    @livewire('rol-controller')


@endsection

resources/views/admin/roles/listar.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                        <li class="breadcrumb-item active">Starter</li>
                    </ol>
                </div>
                <h4 class="page-title">Roles</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="form-group">
                <label for="inputPassword2" class="sr-only">Search</label>
                <input type="search" class="form-control" id="inputPassword2" placeholder="Search...">
            </div>
        </div>
        <div class="col-sm-6 col-md-6 col-lg-6 ">

                <!--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal">Info
                    Alert</button>-->
                <button type="button" class="btn btn-success waves-effect waves-light mr-1 float-right" data-toggle="modal"
                    data-target="#con-close-modal"><i class="mdi mdi-plus-circle mr-1"></i> AGREGAR</button>

        </div><!-- end col-->

        <div class="responsive-table-plugin col-12">
            <div class="card-box">

                {{--<div class="table-rep-plugin">--}}
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>N°</th>
                                    <th>ROL</th>
                                    <th>DESCRIPCIÓN </th>
                                    <th>FECHA CREACIÓN</th>
                                    <th>FECHA ACTUALIZACIÓN</th>
                                    <th>OPCIONES</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($roles as $rol)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <th><span class="co-name text-uppercase">{{$rol->rol}}</span></th>
                                    <td>{{$rol->descripcion}}</td>
                                    <td>{{$rol->created_at}}</td>
                                    <td>{{$rol->updated_at}}</td>
                                    <td>
                                        {{--<button type="button" class="btn btn-info" data-toggle="modal"
                                            data-target="#info-alert-modal{{ $loop->iteration }}">Info
                                            Alert</button>--}}
                                        <button wire:click="edit({{$rol->id}})" type="button"
                                            class="btn btn-blue btn-sm waves-effect waves-light"><i
                                                class="fas fa-pen"></i></button>
                                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                                            data-target="#info-alert-modal{{ $loop->iteration }}"><i
                                                class="fas fa-trash-alt"></i></button>
                                    </td>
                                </tr>
                                @include('admin.common.delete-dialog')
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{--
                </div>--}}
                <nav class="p-1">
                    <ul class="justify-content-start">
                        {{$roles->firstItem()}} a {{$roles->lastItem()}} de {{$roles->total()}}entradas
                    </ul>
                    <ul class="pagination justify-content-end">
                        {{$roles->links()}}
                    </ul>
                </nav>
            </div>
        </div>

    </div>

    @include('admin.roles.create')


</div>

<script>
    document.addEventListener('DOMContentLoaded', function (){
        window.livewire.on('rol-add', msg=>{
            $('#con-close-modal').modal('hide')
        });

        window.livewire.on('show-modal', msg=>{
            $('#con-close-modal').modal('show')
        });
    });
</script>

resources/views/admin/roles/update.blade.php
<?php