routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;

use App\Http\livewire\RolController;
use App\Http\livewire\ServicioController;
use App\Http\livewire\TipoPacienteController;
use App\Http\livewire\EspecialidadController;
use App\Http\Livewire\MedicamentoController;
use App\Http\Livewire\RecetaMedicaController;
use App\Http\Livewire\MedicoController;
use App\Http\Livewire\PacienteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/admin', function () {
    return view('admin.dashboard');
});*/



Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});


Route::get('/login', [App\Http\Controllers\LoginController::class, 'show'])->name('login');
Route::post('/login', [App\Http\Controllers\LoginController::class, 'login'])->name('login.perform');

Route::middleware(['middleware' => 'auth'])->group(function() {
    //convocatoria
    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'admin'],
        function () {

            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            //Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.rol');
            Route::resource('/roles', RolController::class);
            Route::resource('/servicios', ServicioController::class);
            Route::resource('/tipo-paciente', TipoPacienteController::class);
            Route::resource('/especialidad', EspecialidadController::class);
            Route::resource('/medicamento', MedicamentoController::class);
            Route::resource('/receta-medica', RecetaMedicaController::class);
            Route::resource('/medicos', MedicoController::class);
            Route::resource('/pacientes', PacienteController::class);
        });

    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'empleado'],
        function () {

            //Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            //Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index1'])->name('home1');

        });
    });

//Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    /*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');*/
//});

app/Models/Especialidad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Especialidad extends Model
{
    use HasFactory;
    protected $fillable = ['id', 'nombre', 'descripcion', 'estado', 'created_at', 'updated_at'];

    public function medicos(){
        return $this->hasMany('App\Models\Medico');
    }
}

app/Http/Livewire/EspecialidadController.php
<?php

namespace App\Http\Livewire;

use App\Models\Especialidad;
use Livewire\Component;
use Livewire\WithPagination;

class EspecialidadController extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $listeners = ['render', 'destroy'];

    public $selected_id;
    public $accion;
    public $nombre, $descripcion, $estado, $created_at, $updated_at;
    public $search;
    public $cantidad = 10;
    public $sort = 'id';
    public $order = 'desc';


    protected $rules = [
        'nombre'       => 'required',
        'nombre' => 'required|alpha',
        

        'descripcion'   => 'required',
    ];

    protected $msjError=[
        'nombre.required' => 'El campo tipo nombre especialidad es obligatorio.',
        'nombre.alpha' => 'El nombre solo debe contener letras.',
       
        
        'descripcion.required' => 'El campo descripción es obligatorio.'

    ];

    public function render()
    {
        $especialidades = Especialidad::where('nombre', 'like', '%' . $this->search . '%')
            ->orderBy($this->sort, $this->order)
            ->paginate($this->cantidad);
        return view('admin.especialidad.view', compact('especialidades'));
    }

    public function index()
    {
        return view('admin.especialidad.index');
    }

    public function create(){
        $this->resetUI();
        $this->emit('show-modal-especialidad', 'mostrar modal');
    }

    public function store(){
        $this->validate($this->rules, $this->msjError);
        Especialidad::create([
            'nombre' => $this->nombre,
            'descripcion' => $this->descripcion,
            'estado' => 1,
            'created_at'=>now(),
            'updated_at'=>null
        ]);

        $this->resetUI();
        $this->emit('especialidad-add-close', 'Servicio Registrado');
        $this->dispatchBrowserEvent('alert',
            ['type' => 'success',  'message' => 'Registro exitoso!']);

    }

    public function edit($id){
        $this->selected_id = $id;
        $especidad = Especialidad::find($id);
        $this->nombre = $especidad->nombre;
        $this->descripcion =$especidad->descripcion;
        $this->created_at =$especidad->created_at;
        $this->emit('show-modal-especialidad', 'mostrar modal');
    }

    public function update()
    {
        $this->validate($this->rules, $this->msjError);

        if ($this->selected_id) {
            $record = Especialidad::find($this->selected_id);
            $record->update([
                'nombre' => $this->nombre,
                'descripcion' => $this->descripcion,
                'created_at'=>null,
                'updated_at'=>now()
            ]);

            $this->resetUI();
            $this->emit('especialidad-add-close', 'Rol Actualizado');
            $this->dispatchBrowserEvent('alert',
                ['type' => 'success',  'message' => 'Actualización exitoso!']);
        }
    }

    public function deleteForm($id, $accion){
        $this->selected_id = $id;
        $this->accion = $accion;
        $this->emit('info-alert-modal', 'mostrar modal');
    }

    public function cancelarEliminado(){
        $this->selected_id = null;
        $this->emit('info-alert-modal-close', 'mostrar modal');
    }

    public function closeModal(){
        $this->resetUI();
        $this->emit('especialidad-add-close', 'Rol Actualizado');
    }

    public function eliminar()
    {
        if ($this->selected_id) {
            if ($this->accion=='desactivar'){
                $record = Especialidad::find($this->selected_id);
                $record->update([
                    'estado' => 0
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Eliminado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Eliminado!']);
            } else{
                $record = Especialidad::find($this->selected_id);
                $record->update([
                    'estado' => 1
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Activado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Activado!']);
            }

        }
    }

    public function resetUI(){
        $this->nombre=null;
        $this->descripcion=null;
        $this->selected_id=null;
        $this->accion=null;
        $this->resetValidation();
    }
}

resources/views/admin/especialidad/form.blade.php
<div wire:ignore.self id="con-close-modal-especialidad" class="modal fade" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                @if(!$selected_id)
                    {{--<h4 class="modal-title">{{$title}}</h4>--}}
                    <h4 class="modal-title">ESPECIALIDAD | REGISTRAR</h4>
                @else
                    <h4 class="modal-title">ESPECIALIDAD | EDITAR</h4>
                @endif
                {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Nombre Especialidad</label>
                            <input wire:model.lazy="nombre" type="text" class="form-control" id="field-3" placeholder="Nombre Especialidad" maxlength="150" oninput="this.value = this.value.replace(/[^a-zA]/,'')">
                            @error('nombre')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group no-margin">
                            <label for="field-7" class="control-label">Descripción</label>
                            <textarea wire:model.lazy="descripcion" class="form-control" id="field-7" placeholder="Descripción"maxlength="250" ></textarea>
                            @error('descripcion')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button wire:click="closeModal()" type="button" class="btn btn-secondary waves-effect">CANCELAR</button>
                @if(!$selected_id)
                    <button wire:click.prevent="store()" type="button" class="btn btn-primary waves-effect waves-light">REGISTRAR</button>
                @else
                    <button wire:click.prevent="update()" type="button" class="btn btn-primary waves-effect waves-light">ACTUALIZAR</button>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/admin/especialidad/index.blade.php
@extends('admin.layout.app_admin')
@section('content')
    @livewire('especialidad-controller')
@endsection

resources/views/admin/especialidad/view.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                        <li class="breadcrumb-item active">Starter</li>
                    </ol>
                </div>
                <h4 class="page-title">Tipo Paciente</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-6 col-md-8 col-lg-8">
                        <div class="form-group">
                            <label for="inputPassword2" class="sr-only">Search</label>
                            <input wire:model="search" type="search" class="form-control" id="inputPassword2" placeholder="Search...">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="text-lg-right mt-3 mt-lg-0">
                            {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal">Info Alert</button>--}}
                            <button wire:click="create()" type="button" class="btn btn-success waves-effect waves-light mr-1" ><i class="mdi mdi-plus-circle mr-1"></i> AGREGAR</button>
                        </div>
                    </div><!-- end col-->
                </div>
                <div class="responsive-table-plugin">
                    {{--<div class="table-rep-plugin">--}}
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>N°</th>
                                <th>NOMBRE ESPECIALIDAD</th>
                                <th>DESCRIPCIÓN </th>
                                <th>FECHA CREACIÓN</th>
                                <th>ESTADO</th>
                                <th>OPCIONES</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($especialidades as $especialidad)
                                <tr>
                                    <td>{{(($especialidades->currentpage()-1)*$cantidad) + $loop->iteration }}</td>
                                    <th><span class="co-name">{{$especialidad->nombre}}</span></th>
                                    <td>{{$especialidad->descripcion}}</td>
                                    <td>{{$especialidad->created_at}}</td>
                                    <td>
                                        @if($especialidad->estado==1)
                                        <span class="badge bg-soft-success text-success">ACTIVADO</span>
                                        @else
                                            <span class="badge bg-soft-danger text-danger">DESACTIVADO</span>
                                        @endif
                                    </td>
                                    <td>
                                        {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal{{ $loop->iteration }}">Info Alert</button>--}}
                                        <button wire:click="edit({{$especialidad->id}})" type="button" class="btn btn-blue btn-sm waves-effect waves-light"><i class="fas fa-pen"></i></button>
                                        @if($especialidad->estado==1)
                                        <button wire:click="deleteForm({{$especialidad->id}}, 'desactivar')" type="button" class="btn btn-danger btn-sm" ><i class="fas fa-trash-alt"></i></button>
                                        @else
                                            <button wire:click="deleteForm({{$especialidad->id}}, 'activar')" type="button" class="btn btn-success btn-sm" ><i class="fas fa-check-circle"></i></button>
                                        @endif
                                    </td>
                                </tr>
                                @include('admin.common.delete-dialog')
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{--</div>--}}
                    <nav class="p-1">
                        <ul class="justify-content-start">
                            {{$especialidades->firstItem()}}
                            a {{$especialidades->lastItem()}} de {{$especialidades->total()}} entradas
                        </ul>
                        <ul class="pagination justify-content-end">

                            {{$especialidades->links()}}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    @include('admin.especialidad.form')


</div>

<script>
    document.addEventListener('DOMContentLoaded', function (){
        window.livewire.on('especialidad-add-close', msg=>{
            $('#con-close-modal-especialidad').modal('hide')
        });

        window.livewire.on('show-modal-especialidad', msg=>{
            $('#con-close-modal-especialidad').modal('show')
        });

        window.livewire.on('info-alert-modal', msg=>{
            $('#info-alert-modal').modal('show')
        });

        window.livewire.on('info-alert-modal-close', msg=>{
            $('#info-alert-modal').modal('hide')
        });
    });
</script>