routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\LoginController;

use App\Http\livewire\RolController;
use App\Http\livewire\ServicioController;
use App\Http\livewire\TipoPacienteController;
use App\Http\livewire\EspecialidadController;
use App\Http\Livewire\MedicamentoController;
use App\Http\Livewire\RecetaMedicaController;
use App\Http\Livewire\MedicoController;
use App\Http\Livewire\PacienteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
Route::get('/admin', function () {
    return view('admin.dashboard');
});*/



Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});


Route::get('/login', [App\Http\Controllers\LoginController::class, 'show'])->name('login');
Route::post('/login', [App\Http\Controllers\LoginController::class, 'login'])->name('login.perform');

Route::middleware(['middleware' => 'auth'])->group(function() {
    //convocatoria
    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'admin'],
        function () {

            Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            //Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index'])->name('admin.rol');
            Route::resource('/roles', RolController::class);
            Route::resource('/servicios', ServicioController::class);
            Route::resource('/tipo-paciente', TipoPacienteController::class);
            Route::resource('/especialidad', EspecialidadController::class);
            Route::resource('/medicamento', MedicamentoController::class);
            Route::resource('/receta-medica', RecetaMedicaController::class);
            Route::resource('/medicos', MedicoController::class);
            Route::resource('/pacientes', PacienteController::class);
        });

    Route::group([
        //'namespace' => 'admin',
        'middleware' => 'empleado'],
        function () {

            //Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
            //Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');

            Route::get('/administrar/rol', [App\Http\Controllers\HomeController::class, 'index1'])->name('home1');

        });
    });

//Route::middleware(['auth', 'role:1'])->group(function () {
    // User is authentication and has admin role
    /*Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::post('/logout', [App\Http\Controllers\LogoutController::class, 'perform'])->name('logout');*/
//});

app/Models/Medico.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medico extends Model
{
    use HasFactory;

    protected $fillable = ['id','dni', 'nombres', 'apellido_paterno', 'apellido_materno', 'codigo_medicos', 'especialidad_id', 'estado', 'created_at', 'updated_at'];

    public function especialidad()
    {
        return $this->belongsTo('App\models\Especialidad');
    }
}

app/Http/Livewire/MedicoController.php
<?php

namespace App\Http\Livewire;

use App\Models\Especialidad;
use App\Models\Medico;
use App\Models\Paciente;
use Livewire\Component;
use Livewire\WithPagination;

class MedicoController extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    protected $listeners = ['render', 'destroy'];

    public $selected_id;
    public $accion;
    public $dni, $nombres, $especialidad_id, $apellido_materno, $apellido_paterno, $codigo_medicos, $created_at, $updated_at;
    public $search;
    public $cantidad = 10;
    public $sort = 'id';
    public $order = 'desc';


    protected $rules = [
        'dni'               => 'required',
        'nombres'           => 'required',
        'apellido_materno'  => 'required',
        'apellido_paterno'  => 'required',
        'especialidad_id'  => 'required',
        'codigo_medicos'  => 'required',
    ];

    protected $msjError=[
        'dni.required' => 'El campo DNI es obligatorio.',
        'nombres.required' => 'El campo nombres es obligatorio.',
        'apellido_materno.required' => 'El campo apellido materno es obligatorio.',
        'apellido_paterno.required' => 'El campo apellido paterno es obligatorio.',
        'especialidad_id.required' => 'El campo especialidad es obligatorio.',
        'codigo_medicos.required' => 'El campo código de medico es obligatorio.'
    ];

    public function render()
    {

        //$escritores = Paciente::with('personas')->get();
        //dd($escritores);
        $cbo_especialidad = Especialidad::where('estado', 1)->get();
        $medicos = Medico::where('nombres', 'like', '%' . $this->search . '%')
            ->orderBy($this->sort, $this->order)
            ->paginate($this->cantidad);
        return view('admin.medicos.view', compact('medicos', 'cbo_especialidad'));
    }

    public function index()
    {
        return view('admin.medicos.index');
    }

    public function create(){
        $this->resetUI();
        $this->emit('show-modal-medico', 'mostrar modal');
    }

    public function store(){
        $this->validate($this->rules, $this->msjError);
        Medico::create([
            'dni' => $this->dni,
            'nombres' => $this->nombres,
            'apellido_paterno' => $this->apellido_paterno,
            'apellido_materno' => $this->apellido_materno,
            'codigo_medicos' => $this->codigo_medicos,
            'especialidad_id' => $this->especialidad_id,
            'estado' => 1,
            'created_at'=>now(),
            'updated_at'=>null
        ]);

        $this->resetUI();
        $this->emit('medico-add-close', 'Servicio Registrado');
        $this->dispatchBrowserEvent('alert',
            ['type' => 'success',  'message' => 'Registro exitoso!']);

    }

    public function edit($id){
        $this->selected_id = $id;
        $medico = Medico::find($id);
        $this->dni = $medico->dni;
        $this->nombres = $medico->nombres;
        $this->apellido_paterno = $medico->apellido_paterno;
        $this->apellido_materno = $medico->apellido_materno;
        $this->especialidad_id = $medico->especialidad_id;
        $this->codigo_medicos =$medico->codigo_medicos;
        $this->created_at =$medico->created_at;
        $this->emit('show-modal-medico', 'mostrar modal');
    }

    public function update()
    {
        $this->validate($this->rules, $this->msjError);

        if ($this->selected_id) {
            $record = Medico::find($this->selected_id);
            $record->update([
                'dni' => $this->dni,
                'nombres' => $this->nombres,
                'apellido_paterno' => $this->apellido_paterno,
                'apellido_materno' => $this->apellido_materno,
                'especialidad_id' => $this->especialidad_id,
                'codigo_medicos' => $this->codigo_medicos,
                //'created_at'=>null,
                'updated_at'=>now()
            ]);

            $this->resetUI();
            $this->emit('medico-add-close', 'Rol Actualizado');
            $this->dispatchBrowserEvent('alert',
                ['type' => 'success',  'message' => 'Actualización exitoso!']);
        }
    }

    public function deleteForm($id, $accion){
        $this->selected_id = $id;
        $this->accion = $accion;
        $this->emit('info-alert-modal', 'mostrar modal');
    }

    public function cancelarEliminado(){
        $this->selected_id = null;
        $this->emit('info-alert-modal-close', 'mostrar modal');
    }

    public function closeModal(){
        $this->resetUI();
        $this->emit('medico-add-close', 'Rol Actualizado');
    }

    public function eliminar()
    {
        if ($this->selected_id) {
            if ($this->accion=='desactivar'){
                $record = Medico::find($this->selected_id);
                $record->update([
                    'estado' => 0
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Eliminado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Eliminado!']);
            } else{
                $record = Medico::find($this->selected_id);
                $record->update([
                    'estado' => 1
                ]);

                $this->resetUI();
                $this->emit('info-alert-modal-close', 'Registro Activado');
                $this->dispatchBrowserEvent('alert',
                    ['type' => 'success',  'message' => 'Registro Activado!']);
            }

        }
    }

    public function resetUI(){
        $this->dni=null;
        $this->nombres=null;
        $this->apellido_materno=null;
        $this->apellido_paterno=null;
        $this->codigo_medicos=null;
        $this->especialidad_id=null;
        $this->selected_id=null;
        $this->accion=null;
        $this->resetValidation();
    }
}

resources/views/admin/medicos/form.blade.php
<div wire:ignore.self id="con-close-modal-medico" class="modal fade" tabindex="-1" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                @if(!$selected_id)
                    {{--<h4 class="modal-title">{{$title}}</h4>--}}
                    <h4 class="modal-title">MEDICOS | REGISTRAR</h4>
                @else
                    <h4 class="modal-title">MEDICOS | EDITAR</h4>
                @endif
                {{--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="field-3" class="control-label">DNI</label>
                            <input wire:model.lazy="dni" type="text" class="form-control" id="field-3" placeholder="DNI">
                            @error('dni')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Nombres</label>
                            <input wire:model.lazy="nombres" type="text" class="form-control" id="field-3" placeholder="Nombres">
                            @error('nombres')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Apellido Paterno</label>
                            <input wire:model.lazy="apellido_paterno" type="text" class="form-control" id="field-3" placeholder="Apellido Paterno">
                            @error('apellido_paterno')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Apellido Materno</label>
                            <input wire:model.lazy="apellido_materno" type="text" class="form-control" id="field-3" placeholder="Apellido Materno">
                            @error('apellido_materno')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Código medico</label>
                            <input wire:model.lazy="codigo_medicos" type="text" class="form-control" id="field-3" placeholder="Código medico">
                            @error('codigo_medicos')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                    {{--<div class="col-md-6">
                        <div class="form-group">
                            <label for="field-3" class="control-label">Especialidad</label>
                            <input wire:model.lazy="especialidad_id" type="text" class="form-control" id="field-3" placeholder="Especialidad">
                            @error('especialidad_id')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>--}}
                    <div class="col-lg-6">
                        <div class="form-group mb-0">
                            <label for="select-code-language">Dropdown Header</label>
                            <select wire:model.lazy="especialidad_id" class="custom-select form-control" >
                                <option selected>Open this select menu</option>
                                @foreach($cbo_especialidad as $item)
                                <option value="{{$item->id}}">{{$item->nombre}}</option>
                                @endforeach
                            </select>
                            @error('especialidad_id')
                            <span class="text-sm text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button wire:click="closeModal()" type="button" class="btn btn-secondary waves-effect">CANCELAR</button>
                @if(!$selected_id)
                    <button wire:click.prevent="store()" type="button" class="btn btn-primary waves-effect waves-light">REGISTRAR</button>
                @else
                    <button wire:click.prevent="update()" type="button" class="btn btn-primary waves-effect waves-light">ACTUALIZAR</button>
                @endif
            </div>
        </div>
    </div>
</div>

resources/views/admin/medicos/index.blade.php
@extends('admin.layout.app_admin')
@section('content')
    @livewire('medico-controller')
@endsection

resources/views/admin/medicos/view.blade.php
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">UBold</a></li>
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Pages</a></li>
                        <li class="breadcrumb-item active">Starter</li>
                    </ol>
                </div>
                <h4 class="page-title">Medicos</h4>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-6 col-md-8 col-lg-8">
                        <div class="form-group">
                            <label for="inputPassword2" class="sr-only">Search</label>
                            <input wire:model="search" type="search" class="form-control" id="inputPassword2" placeholder="Search...">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="text-lg-right mt-3 mt-lg-0">
                            {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal">Info Alert</button>--}}
                            <button wire:click="create()" type="button" class="btn btn-success waves-effect waves-light mr-1" ><i class="mdi mdi-plus-circle mr-1"></i> AGREGAR</button>
                        </div>
                    </div><!-- end col-->
                </div>
                <div class="responsive-table-plugin">
                    {{--<div class="table-rep-plugin">--}}
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>N°</th>
                                <th>DNI</th>
                                <th>NOMBRES</th>
                                <th>APELLIDO PATERNO</th>
                                <th>APELLIDO MATERNO</th>
                                <th>CODIGO MEDICO</th>
                                <th>ESPECIALIDAD</th>
                                <th>FECHA CREACIÓN</th>
                                <th>ESTADO</th>
                                <th>OPCIONES</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($medicos as $medico)
                                <tr>
                                    <td>{{(($medicos->currentpage()-1)*$cantidad) + $loop->iteration }}</td>
                                    <th class="text-uppercase"><span class="co-name">{{$medico->dni}}</span></th>
                                    <td>{{$medico->nombres}}</td>
                                    <td>{{$medico->apellido_paterno}}</td>
                                    <td>{{$medico->apellido_materno}}</td>
                                    <td>{{$medico->codigo_medicos}}</td>
                                    <td>{{$medico->especialidad->nombre}}</td>
                                    <td>{{$medico->created_at}}</td>
                                    <td>
                                        @if($medico->estado==1)
                                        <span class="badge bg-soft-success text-success">ACTIVADO</span>
                                        @else
                                            <span class="badge bg-soft-danger text-danger">DESACTIVADO</span>
                                        @endif
                                    </td>
                                    <td>
                                        {{--<button type="button" class="btn btn-info" data-toggle="modal" data-target="#info-alert-modal{{ $loop->iteration }}">Info Alert</button>--}}
                                        <button wire:click="edit({{$medico->id}})" type="button" class="btn btn-blue btn-sm waves-effect waves-light"><i class="fas fa-pen"></i></button>
                                        @if($medico->estado==1)
                                        <button wire:click="deleteForm({{$medico->id}}, 'desactivar')" type="button" class="btn btn-danger btn-sm" ><i class="fas fa-trash-alt"></i></button>
                                        @else
                                            <button wire:click="deleteForm({{$medico->id}}, 'activar')" type="button" class="btn btn-success btn-sm" ><i class="fas fa-check-circle"></i></button>
                                        @endif
                                    </td>
                                </tr>
                                @include('admin.common.delete-dialog')
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{--</div>--}}
                    <nav class="p-1">
                        <ul class="justify-content-start">
                            {{$medicos->firstItem()}}
                            a {{$medicos->lastItem()}} de {{$medicos->total()}} entradas
                        </ul>
                        <ul class="pagination justify-content-end">

                            {{$medicos->links()}}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    @include('admin.medicos.form')


</div>

<script>
    document.addEventListener('DOMContentLoaded', function (){
        window.livewire.on('medico-add-close', msg=>{
            $('#con-close-modal-medico').modal('hide')
        });

        window.livewire.on('show-modal-medico', msg=>{
            $('#con-close-modal-medico').modal('show')
        });

        window.livewire.on('info-alert-modal', msg=>{
            $('#info-alert-modal').modal('show')
        });

        window.livewire.on('info-alert-modal-close', msg=>{
            $('#info-alert-modal').modal('hide')
        });
    });
</script>